# src/orin/core/scheduler.py
"""
orin.core.scheduler – Telemetry Collection Automation Manager
=============================================================
Manages recurring local automation by installing or removing cron schedule entries
at system-wide (/etc/cron.d/orin) or user-level (crontab) layers.
"""
import os
import sys
import shutil
import subprocess
from pathlib import Path

CRON_D_FILE = Path("/etc/cron.d/orin")


def get_orin_path() -> str:
    """Resolve the absolute path to the active orin executable binary."""
    path = shutil.which("orin")
    if path:
        return str(Path(path).resolve())
    # Fallback to current execution binary context
    argv0 = Path(sys.argv[0]).resolve()
    if argv0.name == "orin":
        return str(argv0)
    return "/usr/local/bin/orin"


def install_schedule(db_path: Path, interval_minutes: int) -> None:
    """Install a recurring automation cron rule at the system or user layer."""
    db_path = Path(db_path).resolve()
    orin_path = get_orin_path()
    
    # 1. Attempt system-wide cron installation if /etc/cron.d exists
    if os.path.exists("/etc/cron.d"):
        try:
            cron_content = (
                f"# Orin Forensic Engine Automation Schedule\n"
                f"# Auto-generated by 'orin schedule'. Do not edit manually.\n"
                f"*/{interval_minutes} * * * * root {orin_path} --database {db_path} collect 2>&1 | logger -t orin-collect && {orin_path} --database {db_path} analyze 2>&1 | logger -t orin-analyze\n"
            )
            CRON_D_FILE.write_text(cron_content)
            print(f"[+] System-wide automation cron job installed successfully at: {CRON_D_FILE}")
            print(f"[+] Interval: every {interval_minutes} minutes")
            print("[+] Logs will stream to syslog (inspect with 'journalctl -t orin-collect')")
            return
        except PermissionError:
            # If not running as root or directory not writable, fall through to user crontab
            pass

    # 2. Fall back to user-level crontab modification
    try:
        cron_rule = f"*/{interval_minutes} * * * * {orin_path} --database {db_path} collect 2>&1 | logger -t orin-collect && {orin_path} --database {db_path} analyze 2>&1 | logger -t orin-analyze"
        
        try:
            current_cron = subprocess.check_output(["crontab", "-l"], stderr=subprocess.DEVNULL).decode()
        except subprocess.CalledProcessError:
            current_cron = ""

        # Clean existing Orin entries to prevent duplicate schedule loops
        new_lines = []
        for line in current_cron.splitlines():
            if "orin collect" not in line and "orin-collect" not in line and "Orin Forensic Engine Automation" not in line:
                new_lines.append(line)

        new_lines.append("# Orin Forensic Engine Automation Schedule")
        new_lines.append(cron_rule)
        
        new_cron = "\n".join(new_lines) + "\n"
        
        p = subprocess.Popen(["crontab", "-"], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        stdout, stderr = p.communicate(input=new_cron.encode())
        
        if p.returncode == 0:
            print("[+] User-level automation cron job installed successfully.")
            print("[+] Interval: every {interval_minutes} minutes")
            print("[+] Logs will stream to syslog (inspect with 'journalctl -t orin-collect')")
        else:
            print(f"❌ Error: Failed to write user crontab: {stderr.decode().strip()}", file=sys.stderr)
            sys.exit(1)
            
    except Exception as e:
        print(f"❌ Error: Failed to install cron job: {e}", file=sys.stderr)
        sys.exit(1)


def remove_schedule() -> None:
    """Remove all system-wide or user-level Orin automation cron entries."""
    removed = False
    
    # 1. Clean system-wide file
    if CRON_D_FILE.exists():
        try:
            CRON_D_FILE.unlink()
            print(f"[+] System-wide automation cron job removed from: {CRON_D_FILE}")
            removed = True
        except PermissionError:
            print(f"❌ Error: Permission denied removing {CRON_D_FILE}. Run as root.", file=sys.stderr)
            sys.exit(1)

    # 2. Clean user-level crontab
    try:
        try:
            current_cron = subprocess.check_output(["crontab", "-l"], stderr=subprocess.DEVNULL).decode()
        except subprocess.CalledProcessError:
            current_cron = ""

        if current_cron:
            new_lines = []
            has_orin = False
            for line in current_cron.splitlines():
                if "orin collect" in line or "orin-collect" in line or "Orin Forensic Engine Automation" in line:
                    has_orin = True
                else:
                    new_lines.append(line)
                    
            if has_orin:
                new_cron = "\n".join(new_lines) + "\n"
                p = subprocess.Popen(["crontab", "-"], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
                p.communicate(input=new_cron.encode())
                print("[+] User-level automation cron job removed.")
                removed = True
                
    except Exception as e:
        print(f"[-] Warning: Failed to clean user crontab: {e}", file=sys.stderr)

    if not removed:
        print("[*] No active Orin automation schedule was found to remove.")


def show_schedule_status() -> None:
    """Examine system files and crontabs to report the current schedule state."""
    active = False
    
    # 1. Check system-wide file
    if CRON_D_FILE.exists():
        pri45nt(f"[*] Found system-wide automation schedule at: {CRON_D_FILE}")
        print("--- File Contents ---")
        print(CRON_D_FILE.read_text().strip())
        print("---------------------")
        active = True

    # 2. Check user crontab
    try:
        current_cron = subprocess.check_output(["crontab", "-l"], stderr=subprocess.DEVNULL).decode()
        orin_lines = [line for line in current_cron.splitlines() if "orin collect" in line or "orin-collect" in line]
        if orin_lines:
       45     print("[*] Found user-level automation schedule in crontab:")
            for line in orin_lines:
                print(f"  {line}")
            active = True
    except Exception:
        pass

    if not active:
        print("[*] Orin automation is currently: INACTIVE (No schedule installed)")
45